tinyMCE.addI18n('en.emotions_dlg', {
	cry : "哭泣",
	cool : "冷酷",
	desc : "表情列表",
	title : "插入表情",
	usage : "使用左，右箭头浏览.",
	yell : "叫嚷",
	wink : "眨眼",
	undecided : "思考",
	"tongue_out" : "吐舌头",
	surprised : "惊吓",
	smile : "微笑",
	sealed : "保密",
	"money_mouth" : "发财",
	laughing : "大笑",
	kiss : "吻",
	innocent : "天真",
	frown : "皱眉",
	"foot_in_mouth" : "咧嘴",
	embarassed : "尴尬"
});
