tinyMCE.addI18n('en.table_dlg',{
	"rules_border" : "边框",
	"rules_box" : "盒",
	"rules_vsides" : "垂直大小",
	"rules_rhs" : "rhs",
	"rules_lhs" : "lhs",
	"rules_hsides" : "水平大小",
	"rules_below" : "之下",
	"rules_above" : "之上",
	"rules_void" : "空",
	rules : "标尺",
	"frame_all" : "全",
	"frame_cols" : "列",
	"frame_rows" : "行",
	"frame_groups" : "组",
	"frame_none" : "无",
	frame : "边框",
	caption : "表格标题",
	"missing_scope" : "您确定不指定表头单元格的范围吗？如果不指定，部分使用者将很难查看表格内容。",
	"cell_limit" : "已超过限制，最多为{$cells} 单元格。",
	"row_limit" : "已超过限制，最多为 {$rows} 行。",
	"col_limit" : "已超过限制，最多为 {$cols} 列。",
	colgroup : "列组",
	rowgroup : "行组",
	scope : "范围",
	tfoot : "表尾",
	tbody : "表体",
	thead : "表头",
	"row_all" : "更新表格的全部行",
	"row_even" : "更新表格的偶数行",
	"row_odd" : "更新表格的奇数行",
	"row_row" : "更新所在行",
	"cell_all" : "更新全部单元格",
	"cell_row" : "更新当前行的单元格",
	"cell_cell" : "更新当前的单元格",
	th : "表头",
	td : "数据",
	summary : "摘要",
	bgimage : "背景图片",
	rtl : "从右到左",
	ltr : "从左到右",
	mime : "目标 MIME 类型",
	langcode : "语言编码",
	langdir : "书写方向",
	style : "样式",
	id : "ID",
	"merge_cells_title" : "合并单元格",
	bgcolor : "背景颜色",
	bordercolor : "边框颜色",
	"align_bottom" : "底部",
	"align_top" : "顶部",
	valign : "垂直对齐方式",
	"cell_type" : "单元格 类别",
	"cell_title" : "单元格 属性",
	"row_title" : "行 属性",
	"align_middle" : "居中对齐",
	"align_right" : "右对齐",
	"align_left" : "左对齐",
	"align_default" : "默认",
	align : "对齐方式",
	border : "边框",
	cellpadding : "单元格填充",
	cellspacing : "单元格间距",
	rows : "行数",
	cols : "列数",
	height : "高度",
	width : "宽度",
	title : "插入/编辑 表格",
	rowtype : "行所在的表格位置",
	"advanced_props" : "高级 属性",
	"general_props" : "一般 属性",
	"advanced_tab" : "高级",
	"general_tab" : "一般",
	"cell_col" : "更新当前列的单元格"
});