tinyMCE
		.addI18n(
				'en.advanced',
				{
					"underline_desc" : "下划线 (Ctrl+U)",
					"italic_desc" : "斜体 (Ctrl+I)",
					"bold_desc" : "粗体 (Ctrl+B)",
					dd : "名词解释",
					dt : "名词定义",
					samp : "代码例子",
					code : "代码",
					blockquote : "引用",
					h1:"标题 1",
					h2:"标题 2",
					h3:"标题 3",
					h4:"标题 4",
					h5:"标题 5",
					h6:"标题 6",
					pre : "默认格式",
					address : "地址",
					div : "DIV",
					paragraph : "段落",
					block : "格式",
					fontdefault : "字体",
					"font_size" : "字体大小",
					"style_select" : "样式",
					"anchor_delta_height" : "",
					"anchor_delta_width" : "",
					"charmap_delta_height" : "",
					"charmap_delta_width" : "",
					"colorpicker_delta_height" : "",
					"colorpicker_delta_width" : "",
					"link_delta_height" : "",
					"link_delta_width" : "",
					"image_delta_height" : "",
					"image_delta_width" : "",
					"more_colors" : "更多颜色...",
					"toolbar_focus" : "工具列 - Alt+Q, 编辑器 - Alt-Z, 组件路径 - Alt-X",
					newdocument : "您确认要删除全部内容吗?",
					path : "路径",
					"clipboard_msg" : "复制、剪切和粘贴功能在Mozilla 和 Firefox中无法使用,是否想要浏览更多信息?",
					"blockquote_desc" : "引用",
					"help_desc" : "帮助",
					"newdocument_desc" : "新建文件",
					"image_props_desc" : "图片属性",
					"paste_desc" : "粘贴 (Ctrl+V)",
					"copy_desc" : "复制 (Ctrl+C)",
					"cut_desc" : "剪切 (Ctrl+X)",
					"anchor_desc" : "插入/编辑 锚点",
					"visualaid_desc" : "表格隐藏/显示",
					"charmap_desc" : "插入特殊符号",
					"backcolor_desc" : "选择背景颜色",
					"forecolor_desc" : "选择文本颜色",
					"custom1_desc" : "在此输入您的自定义描述",
					"removeformat_desc" : "清除样式",
					"hr_desc" : "插入水平线",
					"sup_desc" : "上标",
					"sub_desc" : "下标",
					"code_desc" : "编辑 HTML源代码",
					"cleanup_desc" : "删除冗余代码",
					"image_desc" : "插入/编辑 图片",
					"unlink_desc" : "取消链接",
					"link_desc" : "插入/编辑 链接",
					"redo_desc" : "恢复 (Ctrl+Y)",
					"undo_desc" : "撤销 (Ctrl+Z)",
					"indent_desc" : "增加缩进",
					"outdent_desc" : "减少缩进",
					"numlist_desc" : "插入/删除 编号列表",
					"bullist_desc" : "插入/删除 项目符号列表",
					"justifyfull_desc" : "两端对齐",
					"justifyright_desc" : "右对齐",
					"justifycenter_desc" : "居中对齐",
					"justifyleft_desc" : "左对齐",
					"striketrough_desc" : "删除线",
					"help_shortcut" : "按Alt - F10显示工具栏。按alt-0显示帮助",
					"rich_text_area" : "富文本域",
					"shortcuts_desc" : "可用性帮助",
					toolbar : "工具条"
				});